name : Python Testing
on : 
  push:
jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    -name: Download Repository
    uses: actions/checkout@v4
    -name: Install Python
      uses: actions/python@v5
      with:
        python--version:"3.11"
    -name: Install Packages
     run: pip install -r requirements.txt

    -name: Run Tests
     run: pytest